# Nexus Server URL
nexus.url=192.168.56.2:8081

# Repository Name
nexus.repo=vprofile-repo

# Artifact Information
nexus.groupId=devops-cicd
nexus.artifactId=vprofile
nexus.version=
nexus.packaging=war

# Artifact File Location
nexus.artifactFile=vprofile-v2.war

# Download URL
nexus.downloadUrl=http://192.168.56.2:8081/repository/vprofile-repo/devops-cicd/vprofile/${APP_VERSION}/vprofile-${APP_VERSION}.war