##########################################################################################
# SonarQube Project Information
sonar.projectKey=vprofile
sonar.projectName=devops-cicd
sonar.projectVersion=1.0

# Source Code Location
sonar.sources=src

# Test Code (Junit)
sonar.junit.reportsPath=target/surefire-reports/

# Compiled Classes
sonar.java.binaries=target/test-classes/xyz/shrutideep/account/controllerTest/

#
sonar.java.checkstyle.reportPaths=target/checkstyle-result.xml

# SonarQube Server URL
sonar.host.url=http://192.168.56.2:9080

# Authentication Token (better stored in Jenkins credentials)
#sonar.login=SONAR_TOKEN

# Code Coverage (JaCoCo)
sonar.jacoco.reportsPath=target/jacoco.exec

###################################################################################
