# Scan Type
trivy.scanType=fs

# Severity levels that will fail pipeline
trivy.severity=HIGH,CRITICAL

# Exit code if vulnerability found
#trivy.exitCode=1

# Continue code if vulnerability found
trivy.exitCode=0

# Ignore unfixed vulnerabilities
trivy.ignoreUnfixed=true

# Scan 
trivy.scan=vuln

# Skip version checking
trivy.version=--skip-version-check

# Scan timeout
#trivy.timeout=5m

# Format for report
trivy.format1=table
trivy.format2=sarif

# Output report
trivy.sarif=trivy-results.sarif
trivy.table=trivy-results.txt

# Store Artifact
trivy.artifactsarif=trivy-results.sarif
trivy.artifacttable=trivy-results.txt